package web

// EventLabels is a 1:1 copy of search.py's EVENT_LABELS dict so the
// rendered HTML carries identical Korean labels. Pulled out of search.go
// because it's a pure data table — keeping it next to the SQL builder
// just made the file longer with no benefit.
//
// Lookups go through labelFor (in search.go) which falls back to the raw
// event_type when the table doesn't recognize it.
var EventLabels = map[string]string{
	"member_join":                 "멤버 입장",
	"member_leave":                "멤버 퇴장",
	"member_ban":                  "멤버 차단",
	"member_unban":                "멤버 차단 해제",
	"member_update":               "멤버 변경",
	"channel_create":              "채널 생성",
	"channel_delete":              "채널 삭제",
	"channel_update":              "채널 변경",
	"guild_update":                "서버 설정 변경",
	"role_create":                 "역할 생성",
	"role_delete":                 "역할 삭제",
	"role_update":                 "역할 변경",
	"voice_join":                  "음성 입장",
	"voice_leave":                 "음성 퇴장",
	"voice_move":                  "음성 이동",
	"thread_create":               "스레드 생성",
	"thread_delete":               "스레드 삭제",
	"reaction_add":                "반응 추가",
	"reaction_remove":             "반응 제거",
	"invite_create":               "초대 생성",
	"invite_delete":               "초대 삭제",
	"emojis_update":               "이모지 변경",
	"channel_pins_update":         "메시지 고정",
	"message_pin":                 "메시지 고정",
	"message_unpin":               "메시지 고정 해제",
	"bulk_message_delete":         "메시지 일괄 삭제",
	"reaction_clear":              "반응 전체 제거",
	"reaction_clear_emoji":        "반응 이모지 제거",
	"thread_update":               "스레드 변경",
	"thread_member_join":          "스레드 멤버 입장",
	"thread_member_remove":        "스레드 멤버 퇴장",
	"stickers_update":             "스티커 변경",
	"user_update":                 "유저 프로필 변경",
	"guild_join":                  "봇 서버 추가",
	"guild_remove":                "봇 서버 제거",
	"voice_state_change":          "음성 상태 변경",
	"automod_rule_create":         "AutoMod 규칙 생성",
	"automod_rule_update":         "AutoMod 규칙 수정",
	"automod_rule_delete":         "AutoMod 규칙 삭제",
	"automod_action":              "AutoMod 실행",
	"audit_log":                   "감사 로그",
	"scheduled_event_create":      "예약 이벤트 생성",
	"scheduled_event_update":      "예약 이벤트 수정",
	"scheduled_event_delete":      "예약 이벤트 삭제",
	"scheduled_event_user_add":    "예약 이벤트 참가",
	"scheduled_event_user_remove": "예약 이벤트 참가 취소",
	"stage_instance_create":       "스테이지 시작",
	"stage_instance_update":       "스테이지 변경",
	"stage_instance_delete":       "스테이지 종료",
	"integrations_update":         "연동 변경",
	"integration_create":          "연동 추가",
	"integration_update":          "연동 수정",
	"integration_delete":          "연동 삭제",
	"webhooks_update":             "웹훅 변경",
}
